### ISSUE TITLE
Typo in the readme

### ISSUE THREAD

**Issue by ricardo2000y** [arcetri/sts#9]
"Added some comments and fixes to the NIST's paper: The improved **SP300-22** Rev 1a is available."  
SP300-22 ->  SP800-22 
Not super relevant but might aswell let you know. 

Also, if I were to reference this github in an article to whom should I atribue the authorship? The three main contributors mentioned in the ReadMe was my first thought but if another way is intended I will do as expected .

**Comment by lcn2** [comment]
Thank you @ricardo2000y , fixed in commit ea07f03acdd3fa3cc92a8e1c73135ac62e18e55c

**Comment by lcn2** [comment]
> Also, if I were to reference this github in an article to whom should I atribue the authorship? The three main contributors mentioned in the ReadMe was my first thought but if another way is intended I will do as expected .

Both GitHub users @lcn2 and @ricpacca contributed to that PDF document, with additional contributions from Tom Gilgan.   Al 3 of us made contributions to the code base.

**Comment by lcn2** [comment]
Thank you @ricardo2000y for this issue.  We have verified that the typo as been corrected.

**Comment by ricardo2000y** [comment]
> > Also, if I were to reference this github in an article to whom should I atribue the authorship? The three main contributors mentioned in the ReadMe was my first thought but if another way is intended I will do as expected .
> 
> Both GitHub users @lcn2 and @ricpacca contributed to that PDF document, with additional contributions from Tom Gilgan. Al 3 of us made contributions to the code base.

I'll make sure to reference the 3 contributers. 
On a side note, the tool was rather straight forward to use ( at least not the most complicated vs most PRNG/RNG Test Suites anyway). Thanks for the quick reply :D

**Comment by lcn2** [comment]
> > > Also, if I were to reference this github in an article to whom should I atribue the authorship? The three main contributors mentioned in the ReadMe was my first thought but if another way is intended I will do as expected .
> > 
> > 
> > Both GitHub users @lcn2 and @ricpacca contributed to that PDF document, with additional contributions from Tom Gilgan. Al 3 of us made contributions to the code base.
> 
> I'll make sure to reference the 3 contributers. On a side note, the tool was rather straight forward to use ( at least not the most complicated vs most PRNG/RNG Test Suites anyway). Thanks for the quick reply :D



> > > Also, if I were to reference this github in an article to whom should I atribue the authorship? The three main contributors mentioned in the ReadMe was my first thought but if another way is intended I will do as expected .
> > 
> > 
> > Both GitHub users @lcn2 and @ricpacca contributed to that PDF document, with additional contributions from Tom Gilgan. Al 3 of us made contributions to the code base.
> 
> I'll make sure to reference the 3 contributers. On a side note, the tool was rather straight forward to use ( at least not the most complicated vs most PRNG/RNG Test Suites anyway). Thanks for the quick reply :D

You are most welcome.
